# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  configure:
    steps:
      - ./buildconf
      - ./configure

  build:
    steps:
      - make

  test:
    steps:
      - make test-nonflaky

executors:
  ubuntu:
    machine:
      image: ubuntu-2004:202010-01

jobs:
  basic:
    executor: ubuntu
    steps:
      - configure
      - build
      - test

workflows:
  all:
    jobs:
      - basic
